# Generated by Django 3.1.2 on 2021-08-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210825_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-ranking']},
        ),
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='Respuesta'),
        ),
    ]
