# Generated by Django 3.1.2 on 2021-08-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210825_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(default=0, verbose_name='question_id')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
            ],
        ),
    ]
